### ISSUE TITLE
k8s quickstart missing piece - PersistentVolume

### ISSUE THREAD

**Issue by nyrahul** [spiffe/spire-tutorials#48]
While following the [quickstart guide for kubernetes](https://spiffe.io/docs/latest/spire/installing/getting-started-k8s/), my `spire-server` pods were not starting up (always in Pending state) because of the following reason:
```
Warning  FailedScheduling  7m33s (x75 over 87m)  default-scheduler  0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.
```
When I checked the `kubectl get pvc`, I could see that the spire-server claims were not getting bound because there were no `PersistentVolume`s.
It is expected that the user provides the `PersistentVolume` for the volume claims from `spire-server`.

The user has to provision a k8s resource such as:
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv-vol
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
```
* /mnt/data folder should exist
* the storage should be >= 1Gi
* the `storageClassName` has got to be "". I tried `storageClassName: manual` and it didn't work.

With this, it finally worked for me, but I am trying to understand if there is something basic I am missing since this guide must have been followed by many others.

The gist is, without setting up a PersistentVolume, the spire-server won't startup in k8s and this step is not documented nor is a sample PersistentVolume present in the k8s/quickstart folder.
