### ISSUE TITLE
Compose files are missing "pid: host" param for agent

### ISSUE THREAD

**Issue by zeldigas** [spiffe/spire-tutorials#56]
While current example works, they are pretty simple. While trying to try more proper use case - agent is in it's own container and workload in it's dedicated one with docker selector, I spent a lot of time figuring one why I got error 
```
could not resolve caller information
```
After some trial, error and googling around I found similar thing about k8s and indeed putting mentioned param did the trick
```
  spire-agent:
    image: gcr.io/spiffe-io/spire-agent:0.12.0
    depends_on: ["spire-server"]
    hostname: spire-agent
    pid: host
```
Not sure if it should go to this repo or spire itself, but just FYI
